version: "3.8"

#docker-compose up -d && docker attach appwrite

services:
  appwrite:
    image: appwrite/appwrite:1.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./appwrite:/usr/src/code/appwrite:rw"
    entrypoint: install
    stdin_open: true
    tty: true
    container_name: appwrite-semsis
    restart: on-failure
    
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    restart: on-failure
    container_name: frontend
    command: sh -c "sleep 10 && npm start"
    depends_on: 
      - appwrite

volumes:
  node_modules:
    
